### ISSUE TITLE
Serval Version is build the wrong way

### ISSUE THREAD

**Issue by adur1990** [servalproject/serval-dna#100]
The version of serval is determined by parsing the `git rev-list --abbrev-commit --max-count=1 HEAD` output. But if you build Serval not from the serval-dna folder but a different one, this either results in `UNKNOWN-VERSION` or a commit id of another repository.

I found this issue, when i was compiling serval to openWRT, since i run make from the openWRT folder and not from the serval-dna folder.

**Comment by lakeman** [comment]
So we should provide `--git-dir=<path>` and / or `--work-tree=<path>`? (patches welcome)

**Comment by quixotique** [comment]
Fixed in 29a771e3152eb15ba1236d95c4ad758d51d76e41
