### ISSUE TITLE
Serval DNA C code uses ambiguous types

### ISSUE THREAD

**Issue by gardners** [servalproject/serval-dna#11]
We use "long long" etc instead of things like uint_64t

Mantis severity: **minor**
Mantis priority: **normal**
Mantis project: **Core Project**
Product version: **0.09 Shiny**
Can reproduce: **N/A**

**Comment by gardners** [comment]
Originally reported as **[mantis:0000165](http://developer.servalproject.org/mantis/view.php?id=165)** at Tue Apr  3 15:52:11 2012.

**Comment by quixotique** [comment]
Issue migrated from Mantis to GitHub with Mantis status **assigned** and resolution **open** at Tue Sep 11 17:29:01 2012 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 0.91

**Comment by quixotique** [comment]
There are no longer any uses of **long long** except where required to invoke the NaCl API or system or standard library calls.  Issue #73 fixed most if not all signed vs unsigned bugs, and the changes pulled from #70 and subsequent work on warnings will help prevent any type unsafe code from creeping in.
