### ISSUE TITLE
Delete/Update files via RESTful

### ISSUE THREAD

**Issue by adur1990** [servalproject/serval-dna#114]
File update or delete not possible via RESTful like in Batphone (https://github.com/servalproject/batphone/blob/development/src/org/servalproject/rhizome/Rhizome.java#L59)

**Comment by quixotique** [comment]
The way to "remove" a bundle from Rhizome is to update it to have an empty payload.  The code you refer to does exactly this.

The RESTful interface supports making updates to a bundle, including setting the payload to empty.  All relevant tests pass, so closing this issue.
