### ISSUE TITLE
Compile error meshms_cli.c (rasp3+)

### ISSUE THREAD

**Issue by b0661** [servalproject/serval-dna#116]
Compile error with gcc on rasp3+ running rasbian stretch:
``
meshms_cli.c: In function ‘app_meshms_list_messages’:
meshms_cli.c:166:65: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
    cli_put_long(context, iter.timestamp ? (now - iter.timestamp):(long)-1, ":");
                                                                 ^
meshms_cli.c:175:63: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
  cli_put_long(context, iter.timestamp ? (now - iter.timestamp):(long)-1, ":");
                                                               ^
meshms_cli.c:186:65: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
    cli_put_long(context, iter.timestamp ? (now - iter.timestamp):(long)-1, ":");
                                                                 ^
meshms_cli.c:195:63: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
  cli_put_long(context, iter.timestamp ? (now - iter.timestamp):(long)-1, ":");
                                                               ^
cc1: all warnings being treated as errors
Makefile:246: recipe for target 'objs_servald/meshms_cli.o' failed
make: *** [objs_servald/meshms_cli.o] Error 1
``

gcc:
``
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 6.2.0-10+rpi1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.2.0 20161027 (Raspbian 6.2.0-10+rpi1)
``

All ok. when removing -Werror. 

Bobby

**Comment by lakeman** [comment]
Should be fixed by d11fef3

**Comment by b0661** [comment]
thanks
