### ISSUE TITLE
WR703N with RFD900 Serval-dna /etc/serval/servald.conf

### ISSUE THREAD

**Issue by potato-cat** [servalproject/serval-dna#122]
I want to try to make a serval-mesh extender with TP-Link's WR703N because it is really cheap.
I buy two routers and change their flash to 8MB, flash openwrt 12.09 into it.
Then I download https://github.com/servalproject/commotion-openwrt as (http://developer.servalproject.org/dokuwiki/doku.php?id=content:meshextender:prototyping_on_mp2) describes, when I compile the saval-dna, an error occurs which says the commit id 928f9c4daedcf851909ee7cf39deb7f2cde59000 can not be found.
I modify it to development branch and compile it successfully.
I install serval.ipk in my routers successfully but when I modify the servald.conf as the document says serval-dna can not run because the servald.conf has many invalid configuration.
Who can help me ?Where can I get a right servald.conf to use my RFD900 for mesh or Where I can get right serval-dna source code?
Thank you very much. My English is not very good and I really hope someone can help me with this question.

**Comment by lakeman** [comment]
First obvious question, what is the contents of servald.conf?

**Comment by potato-cat** [comment]
This is servald.conf in the development.servalproject.org:
```
interfaces.1.encapsulation=single
interfaces.1.file=/dev/ttyUSB0   
interfaces.1.socket_type=stream
interfaces.1.type=catear       
interfaces.2.match=eth0 
interfaces.2.type=ethernet
interfaces.3.match=wlan0  
interfaces.3.type=wifi  
interfaces.4.match=wlan0-1
interfaces.4.type=wifi    
rhizome.datastore_path=/serval
rhizome.idle_timeout=30000    
rhizome.rhizome_mdp_block_size=100
rhizome.max_internal_blob_size=16384
```
like this, but it can not run successfully.
