### ISSUE TITLE
autoreconf fails on macOS Sierra

### ISSUE THREAD

**Issue by gh0st42** [servalproject/serval-dna#127]
Just tried to build serval-dna on a macOS Sierra machine.

```
$ autoreconf -f -i
src/libsodium/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
src/libsodium/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/libsodium/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/libsodium/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
src/libsodium/Makefile.am:1:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
```

libsodium is already installed using brew  but this should not make a difference at this stage since I don't even get to the "configure" step. Prior to  autobuilding libsodium  this was not a problem on macOS.

**Comment by lakeman** [comment]
You might need to install libtool?

**Comment by quixotique** [comment]
What version of autotools?  Which commit of serval-dna?  Please read INSTALL.md, it clearly says:
```
autoreconf -f -i -I m4
```

**Comment by gh0st42** [comment]
libtool is installed:
```
$ which libtool
/usr/bin/libtool
$ libtool
error: /Library/Developer/CommandLineTools/usr/bin/libtool: no output file specified (specify with -o output)
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Library/Developer/CommandLineTools/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
```

And regarding `-I m4` it is optional, adding it also does not help with this problem.

This is the most recent commit in master branch.

**Comment by gh0st42** [comment]
If i revert back to a commit prior to the required libsodium subtree it all builds fine on the machine.
`git checkout 0382e7990e4704991de767057b11c4f11c7b2ba8`

The current version interestingly enough builds just fine on a real old mac with El Capitan installed.

**Comment by quixotique** [comment]
I don't have a Mac with Sierra handy to perform more testing.

The clue is in the error message.  The libsodium Makefile.am definitely contains an LT_INIT line, so it must be that LT_INIT is not in aclocal's search path.  A missing brew package, perhaps?  In Debian, the M4 autoconf macros come in their own package called `autoconf-archive`.

**Comment by gh0st42** [comment]
If you install the libtool version from brew it works, apple command line developer tools version alone doesn't seem to work.

**Comment by quixotique** [comment]
Could you please post the output of `libtool -V`?  Also, which version of Xcode you have installed?  Those pieces of information would help me improve the configure scripts to detect problems like this and at least issue helpful error messages.  I might have to create an `autogen.sh` script.
