### ISSUE TITLE
Build error in Ubuntu while running command make in terminal

### ISSUE THREAD

**Issue by error404-personnotfound** [servalproject/serval-dna#128]
$ make
SERVALD CC jni_common.c
SERVALD CC jni_commandline.c
SERVALD CC jni_instance.c
SERVALD CC jni_server.c
SERVALD CC sqlite-amalgamation-3140200/sqlite3.c
sqlite-amalgamation-3140200/sqlite3.c:1:9: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
         ^
cc1: all warnings being treated as errors
Makefile:254: recipe for target 'objs_servald/sqlite3.o' failed
make: *** [objs_servald/sqlite3.o] Error 1

how to resolve this error

**Comment by AgentConDier** [comment]
@kanishkapillai same here, I commented out the line that was throwing the error. Pretty sure that is not the correct approach, but it seems to work. I'd guess this is caused by an outdated version of gcc or something.

**Comment by lakeman** [comment]
For a quick fix, you should be able to comment out that line.

Looks like Andrew added that pragma to turn off a diagnostic in gcc v7. We probably need to change this to a macro, set by some form of configure test. Or see if upstream sqlite has tidied up the code.

**Comment by AgentConDier** [comment]
Thanks for the quick reply!
I got errors on the following tests:
`118 [ERROR] (msp) Forward TCP connections to a remote server: in setup_netcat6: nc6(1) command is not present`
`119 [ERROR] (msp) Tunnel a tcp connection: in setup_netcat6: nc6(1) command is not present`
`122 [ERROR] (msp) Terminate a connection mid stream: in setup_netcat6: nc6(1) command is not present`
plus all the restful api tests with the same error

Not sure if related

**Comment by lakeman** [comment]
Each test writes a log file into testlog/all/...
The three msp tests are likely to be related to the version of nc, which we
might be mis-detecting
At a guess, I'd say the restful tests are complaining about curl.

**Comment by quixotique** [comment]
I will fix the #pragma line in sqlite3.c to be based on the build configuration.  I will change the configure.in script to detect whether that warning option is supported by the compiler.

**Comment by quixotique** [comment]
It looks like you have not installed the **netcat6** package (to get the nc6 utility) or the **curl** package (to get the curl utility).

If you read the test logs, you will see the cause of the errors.

The doc/Testing.md document describes how to access the test logs.  I suggest you read that document before proceeding any further.

**Comment by AgentConDier** [comment]
I did that. REST Api complained about jq
netcat seems to be installed tho:
`AgentConDier@pine64:~$ netcat`
`This is nc from the netcat-openbsd package. An alternative nc is available
in the netcat-traditional package.`
`usage: nc [-46bCDdhjklnrStUuvZz] [-I length] [-i interval] [-O length]`
`          [-P proxy_username] [-p source_port] [-q seconds] [-s source]`
`          [-T toskeyword] [-V rtable] [-w timeout] [-X proxy_protocol]`
`          [-x proxy_address[:port]] [destination] [port]`
`AgentConDier@pine64:~$ curl`
`curl: try 'curl --help' or 'curl --manual' for more information`
I've installed jq, rerunning tests now.
But what is the difference between netcat and netcat6?
`E: Unable to locate package netcat6`

**Comment by quixotique** [comment]
I presume you are using a version of Ubuntu later than 14.04.  It would have been more helpful if you gave that information in the original bug comment.

The netcat6 package is no longer provided by Ubuntu because the standard OpenBSD nc utility now supports IPv6.  I  have not recently reviewed the Serval test framework's detection/support of the OpenBSD netcat utililty, but I should, because netcat6 it is now deprecated.

**Comment by AgentConDier** [comment]
Yes, I'm on 16.04
Apart from the netcat errors I get 2 FAILs on the tests now: 
`317.RhizomeInsertLarge`
`331.RhizomeImportLarge`
Not sure if related, but I only have 500M of RAM

**Comment by quixotique** [comment]
7ab9bc0 replaces `nc6` with `nc.openbsd`, so no more dependency on the discontinued netcat6 package.
