### ISSUE TITLE
Exposed nodes and hidden nodes.

### ISSUE THREAD

**Issue by error404-personnotfound** [servalproject/serval-dna#130]
How does MDP address the problems of hidden nodes and exposed nodes? How does it ensure QoS?

**Comment by quixotique** [comment]
MDP currently has no QoS support.  We (the senior development team) have discussed QoS in the past, and that is a subject for future experimentation.

@lakeman is better qualified to talk about how our routing table copes with hidden nodes.

**Comment by quixotique** [comment]
Please take this discussion to the mailing list, as we don't want to use GitHub issues as a discussion forum, but to record short-term outstanding work that we plan to do.
