### ISSUE TITLE
servald aborts with "Can't free a subscriber that is being used in routing"

### ISSUE THREAD

**Issue by gardners** [servalproject/serval-dna#136]
This happens on mesh extenders sometimes. Observed with servald commit 86a7ba4.

Log looks like:

INFO: [ 4165] 17:34:12.411    rhizome.datastore_path=/serval-var/rhizome
INFO: [ 4165] 17:34:12.411    rhizome.idle_timeout=30k
FATAL:[ 4165] 17:34:12.411 overlay_address.c:96:free_node()  Can't free a subscriber that is being used by rhizome (69632597424708366E4E37010F3D01DBC7862F10566C87ED0FF8897D32508132, 0x8831a8)
FATAL:[ 4165] 17:34:12.427 servald_main.c:61:crash_handler()  Caught signal SIGABRT (6) Aborted
FATAL:[ 4165] 17:34:12.428 servald_main.c:62:crash_handler()  The following clue may help: no clue
FATAL:[ 4165] 17:34:12.429 performance_timing.c:227:dump_stack()  commandline_main
FATAL:[ 4165] 17:34:12.431 servald_main.c:64:crash_handler()  GDB BACKTRACE
FATAL:[ 4165] 17:34:12.433 GDB execlp("gdb"): No such file or directory
FATAL:[ 4165] 17:34:12.435 gdb exited normally with status 253
INFO: [ 6629] 17:49:51.028 Local date/time: 2018-04-01 17:49:51 +0930
INFO: [ 6629] 17:49:51.028 Serval DNA version: START-35105-g86a7ba4
INFO: [ 6629] 17:49:51.028 Current configuration:
INFO: [ 6629] 17:49:51.028    api.restful.users.lbard.password=lbard
INFO: [ 6629] 17:49:51.028    interfaces.1.match=eth0
INFO: [ 6629] 17:49:51.028    interfaces.1.socket_type=dgram
INFO: [ 6629] 17:49:51.028    interfaces.1.type=ethernet
INFO: [ 6629] 17:49:51.028    interfaces.2.match=eth1
INFO: [ 6629] 17:49:51.028    interfaces.2.socket_type=dgram
INFO: [ 6629] 17:49:51.028    interfaces.2.type=ethernet
INFO: [ 6629] 17:49:51.028    interfaces.3.match=wlan0
INFO: [ 6629] 17:49:51.028    interfaces.3.socket_type=dgram
INFO: [ 6629] 17:49:51.028    interfaces.4.match=wlan1
INFO: [ 6629] 17:49:51.028    interfaces.4.socket_type=dgram
INFO: [ 6629] 17:49:51.028    interfaces.5.match=adhoc0
INFO: [ 6629] 17:49:51.028    interfaces.5.socket_type=dgram
INFO: [ 6629] 17:49:51.028    log.console.level=debug
INFO: [ 6629] 17:49:51.028    log.console.show_time=true
INFO: [ 6629] 17:49:51.028    log.file.directory_path=/serval-var/log
INFO: [ 6629] 17:49:51.028    log.file.level=fatal
INFO: [ 6629] 17:49:51.028    rhizome.datastore_path=/serval-var/rhizome
INFO: [ 6629] 17:49:51.028    rhizome.idle_timeout=30k
FATAL:[ 6629] 17:49:51.028 overlay_address.c:93:free_node()  Can't free a subscriber that is being used in routing (648731D7138773F538B2A78656F72AAD5EAB98900C88CC5C0380F41FE838F54F, 0x9a8ec0, (nil))
FATAL:[ 6629] 17:49:51.043 servald_main.c:61:crash_handler()  Caught signal SIGABRT (6) Aborted
FATAL:[ 6629] 17:49:51.044 servald_main.c:62:crash_handler()  The following clue may help: no clue
FATAL:[ 6629] 17:49:51.044 performance_timing.c:227:dump_stack()  commandline_main
FATAL:[ 6629] 17:49:51.047 servald_main.c:64:crash_handler()  GDB BACKTRACE
FATAL:[ 6629] 17:49:51.049 GDB execlp("gdb"): No such file or directory
FATAL:[ 6629] 17:49:51.051 gdb exited normally with status 253
root@Serval-MeshExtender-0:/serval-var# date
Sun Apr  1 17:26:15 CST 2018

**Comment by gardners** [comment]
Why does free_node get called for a node that is being routed to in the first place?

**Comment by gardners** [comment]
Is it a problem that happens when clock runs backwards?

**Comment by lakeman** [comment]
Returning from main, so the server is exiting? or is this another periodic command?

**Comment by gardners** [comment]
This happens when servald is supposed to be running steady-state.
Probably related to the fact that there is an LBARD talking to it.

Paul.
