### ISSUE TITLE
Allow DNS names in Directory Service client config

### ISSUE THREAD

**Issue by lakeman** [servalproject/serval-dna#18]
In overlay_address.c load_subscriber_address(), refactor to allow **asynchronous** resolution of configured domain names.  This would avoid the problem of hard-configured IP addresses, which may change.

**Comment by lakeman** [comment]
Or Serval Mesh could store a domain name in its preferences, then resolve and set the IP address...

**Comment by lakeman** [comment]
DNS resolution has been implemented as a synchronous process. For the moment, this is a rare enough occurrence that we shouldn't need to worry about the timeout issue.

**Comment by quixotique** [comment]
Warrants at least a TODO comment in the source at the point where it blocks.  Possibly also warrants a new issue (referencing this one).

**Comment by lakeman** [comment]
overlay_link.c, resolve_name() already has a brief TODO.
