### ISSUE TITLE
Rhizome direct tests failing on OSX

### ISSUE THREAD

**Issue by lakeman** [servalproject/serval-dna#25]
The regex passed to sed in get_rhizome_server_port is failing to extract the port number.

**Comment by lakeman** [comment]
This works for me;

```
   local _port=$($SED -n -e "s/.*RHIZOME HTTP SERVER.*START.*port=\([0-9]\{1,\}\).*/\1/p" "${!_logvar}")
```

Though only because the log file has one start log entry.

**Comment by quixotique** [comment]
@lakeman, give 7ee5266998 a go on Mac OS X, let me know if it works or not.

**Comment by lakeman** [comment]
Works for me.
