### ISSUE TITLE
Undertake Multihop calls via Mesh and VOMP

### ISSUE THREAD

**Issue by techxplorer** [servalproject/serval-dna#37]
We need to be able to undertake multihop calls via the Mesh and VOMP

Mantis severity: **block**
Mantis priority: **urgent**
Mantis project: **Core Project**
Product version: **0.09 Shiny**
Target version: **0.09 Shiny**
Related to: **[mantis:0000180](http://developer.servalproject.org/mantis/view.php?id=180)** **Undertake Calls via Mesh and VOMP**
Can reproduce: **always**

**Comment by techxplorer** [comment]
Originally reported as **[mantis:0000181](http://developer.servalproject.org/mantis/view.php?id=181)** at Mon May  7 15:52:51 2012.

**Comment by gardners** [comment]
At Fri Oct 19 20:14:12 2012:

Jeremy has undertaken substantial work on this.
What is outstanding is multi-hop overlay/MDP routing (which is what Jeremy has been working on), and then testing that VoMP calls carry over multiple hops.
It is my understanding that multi-hop overlay/MDP routing is likely to get addressed as part of the current NAF remedial work/integration/documentation contract.

**Comment by quixotique** [comment]
Issue migrated from Mantis to GitHub with Mantis status **assigned** and resolution **open** at Mon Nov  5 18:20:49 2012 using [sp-mantis2github](https://github.com/servalproject/serval-tools/blob/master/bin/sp-mantis2github) version 1.1

**Comment by lakeman** [comment]
Multi-hop vomp calls should work right now, provided MDP packets can be routed successfully. Though the routing engine may be replaced at some point, there's no further work to do with this issue.
