### ISSUE TITLE
tests/server/"Server process does not become a zombie" fails non-deterministically

### ISSUE THREAD

**Issue by gardners** [servalproject/serval-dna#40]
It seems that the test script doesn't allow enough time for servald to always catch the signal.
The failure shows the process state is still sleep, i.e., that it has not yet received the process, as compared to zombie, which is what we would expect if it really wasn't dying for some reason.

**Comment by quixotique** [comment]
Possibly fixed by 5ac394a3c154f303aeee0e9849ca19227b898757.

Let's leave this issue open for a month.  If anybody observes a FAIL of this test case, please report it here, otherwise we can close this issue eventually.

**Comment by quixotique** [comment]
Looks like this is fixed.  Works on Solaris, Linux and Mac OS X.  No spurious failures observed for a month.
