### ISSUE TITLE
Redundent check in vomp_generate_session_id()

### ISSUE THREAD

**Issue by klkblake** [servalproject/serval-dna#42]
In vomp_generate_session_id(), there is the following check:

```
if (session_id==vomp_call_states[i].local.session
    ||session_id==vomp_call_states[i].local.session){
  session_id=0;
  break;
}
```

I presume the second "local" should be "remote"?

**Comment by lakeman** [comment]
Huh, so it is. I don't think there's much point in checking the remote session, but it shouldn't hurt.
