### ISSUE TITLE
Unable to use (Serval 0.90RC1 - Shiny) on HTC Desire HD

### ISSUE THREAD

**Issue by ldmpub** [servalproject/serval-dna#43]
Platform : HCT Desire HD
OS : Android Version    2.3.7 / CyanogenMod
- Install from the apk : Ok
- Activate Wifi on the mobile phone
- First start: Crash at startup with message "Fermeture soudaine de l'application, processus org.servalprojet"
- reboot Mobile Phone
- second start: same crash!
- Manage Android Applications > Serval > Erase data
- third start: looks ok but endless loop on Wifi test and unable to quit application.

I give up for now ;-(.*

Please note that with Serval version yet available on Google Play (serval 0.08) the Wifi test succeed on my phone.
Is there any log I can send to help troubleshout ?

**Comment by lakeman** [comment]
Android has a main log that almost everything is written to. This can be viewed by using the "adb logcat" command line tool from the android SDK. 
There are also a number of applications available on the play store that may be useful in viewing this log, but I haven't tried them;
https://play.google.com/store/apps/details?id=com.xtralogic.android.logcollector
https://play.google.com/store/apps/details?id=com.dngames.remotelogcat
https://play.google.com/store/apps/details?id=org.jtb.alogcat

**Comment by ldmpub** [comment]
Here is the log when Serval crashes at startup:

--------- beginning of /dev/log/main
D/dalvikvm( 1227): GC_EXPLICIT freed 11K, 51% free 2669K/5379K, external 0K/0K, paused 60ms
D/dalvikvm( 1227): GC_EXPLICIT freed <1K, 51% free 2669K/5379K, external 0K/0K, paused 83ms
D/szipinf ( 3071): Initializing inflate state
I/ActivityThread( 3071): Pub org.servalproject.provider: org.servalproject.provider.MainContentProvider
V/MainContentProvider( 3071): content provider created
I/ActivityThread( 3071): Pub org.servalproject.files: org.servalproject.provider.RhizomeProvider
D/dalvikvm( 1227): GC_EXPLICIT freed <1K, 51% free 2669K/5379K, external 0K/0K, paused 63ms
D/ADHOC -> AdhocApplication( 3071): Calling onCreate()
D/dalvikvm( 3071): GC_EXTERNAL_ALLOC freed 82K, 49% free 2792K/5379K, external 0K/0K, paused 35ms
D/AndroidRuntime( 3071): Shutting down VM
W/dalvikvm( 3071): threadid=1: thread exiting with uncaught exception (group=0x40015560)
E/AndroidRuntime( 3071): FATAL EXCEPTION: main
E/AndroidRuntime( 3071): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.servalproject/org.servalproject.Main}: java.lang.NullPointerException
E/AndroidRuntime( 3071):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1768)
E/AndroidRuntime( 3071):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1784)
E/AndroidRuntime( 3071):    at android.app.ActivityThread.access$1500(ActivityThread.java:123)
E/AndroidRuntime( 3071):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:939)
E/AndroidRuntime( 3071):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3071):    at android.os.Looper.loop(Looper.java:130)
E/AndroidRuntime( 3071):    at android.app.ActivityThread.main(ActivityThread.java:3835)
E/AndroidRuntime( 3071):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3071):    at java.lang.reflect.Method.invoke(Method.java:507)
E/AndroidRuntime( 3071):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime( 3071):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
E/AndroidRuntime( 3071):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 3071): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 3071):    at org.servalproject.Main.onCreate(Main.java:107)
E/AndroidRuntime( 3071):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 3071):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1722)
E/AndroidRuntime( 3071):    ... 11 more
W/ActivityManager( 1324):   Force finishing activity org.servalproject/.Main
W/ActivityManager( 1324): Activity pause timeout for HistoryRecord{408d6da0 org.servalproject/.Main}
W/InputManagerService( 1324): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4078c880
I/Process ( 3071): Sending signal. PID: 3071 SIG: 9
I/ActivityManager( 1324): Process org.servalproject (pid 3071) has died.
I/ActivityManager( 1324): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.android.launcher/.Launcher } from pid 1324
D/dalvikvm( 1324): GC_EXTERNAL_ALLOC freed 797K, 37% free 7226K/11463K, external 5692K/5697K, paused 77ms
I/ActivityManager( 1324): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 pkg=org.jtb.alogcat cmp=org.jtb.alogcat/.LogActivity bnds=[0,265][480,361] } from pid 1324
D/dalvikvm( 2990): GC_EXTERNAL_ALLOC freed 152K, 53% free 2837K/5959K, external 1288K/1311K, paused 24ms
W/ActivityManager( 1324): Activity destroy timeout for HistoryRecord{408d6da0 org.servalproject/.Main}

Hope this helps.

**Comment by lakeman** [comment]
Here?
https://github.com/servalproject/batphone/blob/development/src/org/servalproject/Main.java#L107
That's odd.

**Comment by lakeman** [comment]
Please retest with http://developer.servalproject.org/files/Serval-0.90.1.RC1.apk so we can release this fix on the android market.
If there are any further issues on your phone please create a new issue in the servalproject/batphone repository.

**Comment by lakeman** [comment]
More details;
The root cause seems to be a failure to read the package details of our own package. We use this to determine if our application has been upgraded since the last time it has run.
For developers who may be building and deploying multiple times with the same version name, this process checks for the modification time of our apk file.
Since we create a string resource with our version, we can perform a test of the version string without caring about any failures reading the package details.
However if we can't determine the path to our apk file, the "Share Us" feature of Serval Mesh will not function.
