### ISSUE TITLE
When writing new MeshMS (unicast and broadcast), the existing part of the journal sometimes gets zeroed out.

### ISSUE THREAD

**Issue by gardners** [servalproject/serval-dna#51]
The symptom is that no further messages sent from that thread get received.

Strongly suspect the external blob support code broke something.

Currently hampered by the lack of convenient tests of this.  

Will be much easier to debug if we push meshms down into servald, as it will then be able to be tested via our test framework, instead of involving android phones in the loop.

**Comment by lakeman** [comment]
Probably due to experimental code on the serial branch, related to swapping between database storage and external storage on any kind of error.
