### ISSUE TITLE
Build error with HAVE_BCOPY

### ISSUE THREAD

**Issue by rom1v** [servalproject/serval-dna#56]
In `serval-dna` (tested on version 705f414), I execute:

```
./configure && make
```

I have the following error:

```
CC audiodevices.c
In file included from serval.h:118:0,
                 from audiodevices.c:20:
os.h:67:28: error: conflicting types for 'bcopy'
make: *** [audiodevices.o] Error 1
```

The problem comes from `os.h`:

``` c
#ifndef HAVE_BCOPY
__SERVALDNA_OS_INLINE void bcopy(void *src, void *dst, size_t len) {
    memcpy(dst, src, len);
}
#endif                                                  
```

`HAVE_BCOPY` is not defined while `bcopy` exists.

Removing this piece of code works as a workaround (of course it is not the solution).

**Comment by lakeman** [comment]
You need to build a new configure script by running autoreconf.

**Comment by rom1v** [comment]
Thank you, it works ;-)
