### ISSUE TITLE
Move /var/serval-node to /var/lib/serval-node for FHS complience?

### ISSUE THREAD

**Issue by petterreinholdtsen** [servalproject/serval-dna#72]
According to the file hiearcy standard, used by Debian and others to decide where
in the file system a file belong, packages should store their stuff in /var/lib/foo, not /var/foo.  Because of this, I suggest to move /var/serval-node to /var/lib/serval-node.

**Comment by quixotique** [comment]
Probably the path should be more general, eg, `/var/lib/serval/localnode`.  That way, if we ever came to a situation where a node ran more than one Serval daemon (which is possible but not needed by any deployment yet) then we could create several sub directories under `/var/lib/serval`, one for each instance.

**Comment by quixotique** [comment]
For proper FHS compliance, the contents of the Serval instance directory really should be split between several directories:
- the config file should be in `/etc/serval/servald.conf`
- the keyring file should be in `/etc/serval/serval.keyring`
- the PID file should go in `/var/run/servald.pid`
- the log files should go in `/var/log/serval/`
- the Rhizome database files should go in `/var/lib/serval/` or perhaps `/var/cache/serval`

This could be implemented as the standard behaviour if the `SERVALINSTANCE_PATH` env var is not set.  To allow for multiple daemons on the same host, a new env var `SERVALD_CONFIG` could be supported which pointed to a single config file, which in turn would configure the other paths.

If the `SERVALINSTANCE_PATH` env var is set, all paths would be formed as they currently are, to preserve compatibility.  This env var might be deprecated and removed in future.

**Comment by lakeman** [comment]
Some work has been done in ba44088e & 53c1b1c0. Can we close this now?

**Comment by quixotique** [comment]
FHS paths are now fully supported and configurable, but not the `SERVALD_CONFIG` env var discussed above.  See the [FHS Paths](https://github.com/servalproject/serval-dna/blob/development/doc/Servald-Configuration.md#fhs-paths) section of [Servald-Configuration.md](https://github.com/servalproject/serval-dna/blob/development/doc/Servald-Configuration.md) for the details.
