### ISSUE TITLE
Lots of signed/unsigned issues in the code, according to gcc -Wsign-compare

### ISSUE THREAD

**Issue by petterreinholdtsen** [servalproject/serval-dna#73]
I discovered this by adding -Wextra to the build.  There are lots of warnings from the compiler about comparing signed and unsigned integers, which some times can cause problems and unexpected behaviour on some platforms.
There are 332 warnings in total in the development branch at the moment.

I suggest adding -Wextra (or at least -Wsign-compare) to the build, and fixing the issues.

These are the issues currently listed:

nacl/src/crypto_auth_hmacsha256_ref/hmac.c:43:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_auth_hmacsha512256_ref/hmac.c:43:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_hash_sha256_ref/hash.c:39:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_hash_sha512_ref/hash.c:39:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa2012_ref/stream.c:46:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa2012_ref/xor.c:49:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa208_ref/stream.c:46:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa208_ref/xor.c:49:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa20_ref/stream.c:46:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
nacl/src/crypto_stream_salsa20_ref/xor.c:49:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
cli.c:49:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:206:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:210:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:210:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:218:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:221:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:246:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:280:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:282:33: warning: signed and unsigned type in conditional expression [-Wsign-compare]
cli.c:303:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
cli.c:304:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
commandline.c:69:65: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:313:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:480:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:1210:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:1214:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:1219:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:1878:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:2000:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
commandline.c:2102:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_om.c:148:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:188:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:263:7: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_om.c:273:7: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_om.c:322:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:389:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_om.c:408:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_om.c:449:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:491:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:553:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:576:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:584:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_om.c:628:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_schema.h:277:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:287:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:295:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:305:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:322:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:326:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:332:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:334:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:334:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:337:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:337:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:341:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:347:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:349:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:349:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:352:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:352:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:357:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:361:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:367:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:369:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:369:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:372:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:372:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:376:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:384:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:388:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:392:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:396:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:401:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:420:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:424:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:431:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:433:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:433:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:436:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:436:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:461:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:463:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:463:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:466:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:466:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:481:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:335:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:350:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:370:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:434:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:464:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:302:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:303:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:304:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:334:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:336:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:340:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:349:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:351:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:356:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:360:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:369:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:371:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:375:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:387:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:415:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:416:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:417:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:418:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:419:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:433:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:435:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:451:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:463:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:465:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:470:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:471:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:472:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:473:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:474:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:475:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:476:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:477:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:478:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:479:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:480:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:334:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:334:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:349:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:349:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:369:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:369:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:433:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:433:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:463:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.h:463:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
conf_schema.c:509:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
conf_schema.c:518:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
directory_client.c:67:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:186:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
dna_helper.c:355:6: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:399:7: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:415:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:417:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:419:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:421:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:423:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:425:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:427:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:429:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:431:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:433:2: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:436:4: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:441:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:465:6: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:480:4: warning: signed and unsigned type in conditional expression [-Wsign-compare]
dna_helper.c:509:7: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rotbuf.h:133:57: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
keyring.c:242:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1088:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1122:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1157:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1348:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1398:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1407:9: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1450:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1474:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1479:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1482:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1500:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1802:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1876:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:1986:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
keyring.c:2010:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
lsif.c:154:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
mavlink.c:289:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
mavlink.c:330:68: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
meshms.c:257:77: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
meshms.c:268:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
meshms.c:494:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
meshms.c:842:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
mdp_client.c:99:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
os.c:49:12: warning: signed and unsigned type in conditional expression [-Wsign-compare]
os.c:160:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
socket.c:91:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
monitor.c:378:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
monitor.c:520:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
net.c:84:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
net.c:99:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
net.c:126:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
overlay_interface.c:748:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:948:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:1020:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:1024:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:1029:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:1104:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_interface.c:1168:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
overlay_mdp.c:184:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_mdp.c:216:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_mdp.c:512:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_mdp.c:521:10: warning: signed and unsigned type in conditional expression [-Wsign-compare]
overlay_mdp.c:969:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
overlay_mdp.c:1052:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
overlay_packetformats.c:440:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome.c:116:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_database.c:716:3: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_database.c:732:3: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_database.c:1153:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_database.c:1487:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct.c:412:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_direct.c:531:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct_http.c:607:3: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct_http.c:609:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct_http.c:691:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_direct_http.c:693:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct_http.c:788:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_direct_http.c:818:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_fetch.c:156:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:164:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:171:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:187:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:231:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:249:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:262:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:276:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:352:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:369:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:382:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:690:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:809:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:817:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:902:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:955:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1086:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1090:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1090:55: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1138:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1218:5: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_fetch.c:1367:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1399:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_fetch.c:1405:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_http.c:610:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rhizome_store.c:193:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:824:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:826:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:840:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:842:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:1003:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:1118:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:1124:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
rhizome_store.c:1157:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
rotbuf.h:133:57: warning: signed and unsigned type in conditional expression [-Wsign-compare]
serval_packetvisualise.c:85:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:269:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:334:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:337:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:337:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:342:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
serval_packetvisualise.c:343:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
slip.c:378:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
str.c:222:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
str.c:223:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
strbuf_helpers.c:349:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
vomp.c:336:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
vomp.c:353:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
vomp.c:354:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
vomp.c:731:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
vomp.c:735:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
vomp_console.c:232:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
strbuf.h:453:45: warning: signed and unsigned type in conditional expression [-Wsign-compare]
fec-3.0.1/init_rs.h:13:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
tfw_createfile.c:81:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
tfw_createfile.c:87:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
fakeradio.c:68:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
fakeradio.c:133:16: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
fakeradio.c:240:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
fakeradio.c:341:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

**Comment by quixotique** [comment]
Fixed in e921404686ab4bd3e56967566f03db60896743d5, which merge's Petter's changes to enable more compiler warnings.
