### ISSUE TITLE
keyring create does not destroy existing keys.

### ISSUE THREAD

**Issue by b0661** [servalproject/serval-dna#89]
Doing my own tests, keyring create does not destroy existing keys.

Looking at the keyring testcase it seems the output of keyring create is ckecked for keys. 
But doing a keyring list afterwards still shows the two keys.

doc_KeyringCreate="Create keyring destroys existing keys"
test_KeyringCreate() {
    executeOk_servald keyring add ''
    executeOk_servald keyring add ''
    executeOk_servald keyring list
    assert_keyring_list 2
    executeOk_servald keyring create
    executeOk_servald keyring list   <== added
    assert_keyring_list 0
}

**Comment by lakeman** [comment]
True, that doesn't seem to be what keyring create has ever done.

I've broken the test in 032502f80 as you suggested, since it wasn't doing what it said it was.

**Comment by quixotique** [comment]
Fixed by d031747

**Comment by karlgilbert** [comment]
Xhacktly.
