### ISSUE TITLE
Serval RESTful-API misses a call to list all peers

### ISSUE THREAD

**Issue by Rubyfi** [servalproject/serval-dna#96]
I'm currently trying to remove the dependencies on Flask and CLI calls in my [web application](https://github.com/umr-ds/serval-web). Sadly the RESTful-API doesn't support a call that correlates to  calling `servald id allpeers`.

**Comment by quixotique** [comment]
The Peer List REST API is about to be added.  See http://developer.servalproject.org/dokuwiki/doku.php?id=content:activity:nlnet3

**Comment by quixotique** [comment]
The proposed API is https://github.com/servalproject/serval-dna/blob/route-rest-api/doc/REST-API-Route.md
